<!DOCTYPE html>
<html lang="en">
<?php
require base_path("Views/Partials/head.phtml") ?>

<body>
    <?php require base_path("Views/Partials/nav.phtml") ?>
    <div class="min-h-screen flex items-center justify-center bg-gray-100 px-4">
        <form method="POST" action="/categories/store" enctype="multipart/form-data" class="bg-white shadow-xl rounded-2xl p-8 w-full max-w-md space-y-6">
            <h2 class="text-2xl font-bold text-indigo-700 text-center mb-2">Add New Category</h2>
            <div>
                <label for="category-name" class="block text-sm font-semibold text-indigo-700 mb-1">Category Name</label>
                <input
                    type="text"
                    id="category-name"
                    name="category-name"
                    class="w-full px-4 py-2 border border-indigo-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400 transition"
                    placeholder="e.g. Electronics">
                <p class="text-red-500 text-md"><?= $errors['categoryName'] ?? "" ?></p>
            </div>
            <div>
                <label for="category-desc" class="block text-sm font-semibold text-indigo-700 mb-1">Description</label>
                <textarea
                    id="category-desc"
                    name="category-desc"
                    rows="3"
                    class="w-full px-4 py-2 border border-indigo-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-400 transition resize-none"
                    placeholder="Brief description of the category"></textarea>
                <p class="text-red-500 text-md"><?= $errors['categoryDescription'] ?? "" ?></p>
            </div>
            <div>
                <label class="block text-sm font-medium text-indigo-600">Product Image</label>

                <!-- Upload new image -->
                <input type="file" name="image"
                    accept=".png, .jpeg, .jpg"
                    class="mt-2 w-full text-sm text-gray-700 
               file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 
               file:text-sm file:font-semibold 
               file:bg-indigo-50 file:text-indigo-700 
               hover:file:bg-indigo-100 cursor-pointer" />
                <p class="text-red-500 text-md"></p>
            </div>
            <p class="text-red-500 text-me"><?= $errors['categoryImage'] ?? "" ?></p>

            <button
                type="submit"
                class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 rounded-lg transition text-lg shadow-md">
                Add Category
            </button>
        </form>
    </div>
</body>

</html>