<!DOCTYPE html>
<html lang="en">
<?php

use App\Core\Session;

require base_path("Views/Partials/head.phtml");
?>

<body>
  <?php require base_path("Views/Partials/nav.phtml") ?>
  <div class="min-h-screen bg-gray-100 py-8">
    <div class="max-w-7xl mx-auto px-4">

      <div class="max-w-7xl mx-auto px-4">
        <?php if (Session::has("Success-Message")) : ?>
          <h2 class="text-center text-green-600 text-5xl font-extrabold 
       tracking-wide drop-shadow-lg bg-green-100 border border-green-400 
       rounded-xl px-8 py-6 mb-12">
            <?= htmlspecialchars(Session::get("Success-Message")) ?? "" ?>
          </h2>
        <?php endif; ?>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
        <!-- Category Card 1 -->
        <?php foreach ($categories as $category) : ?>
          <div class="bg-white rounded-2xl shadow-lg p-6 flex flex-col items-center transition hover:shadow-xl">
            <img src="<?= htmlspecialchars($category['image']) ?>" alt=" <?= htmlspecialchars($category['categoryName']) ?>" class="mb-4 w-20 h-20 object-contain">
            <h3 class="text-xl font-bold text-indigo-700 mb-2"><?= htmlspecialchars($category['categoryName']) ?></h3>
            <p class="text-gray-500 text-center mb-4"><?= htmlspecialchars($category['description']) ?></p>
            <div class="flex space-x-3 w-full mt-auto">
              <button class="flex-1 bg-blue-500 hover:bg-blue-600 text-white py-2 rounded-lg font-medium transition">
                Show
              </button>
              <a href="/categories/edit/<?= $category['id'] ?>"
                class="flex-1 text-center bg-indigo-500 hover:bg-indigo-600 text-white py-2 rounded-lg font-medium transition">
                Update
              </a>
              <form method="POST" action="/categories/destroy" class="flex-1">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="id" value="<?= $category['id'] ?>">
                <button
                  class="w-full text-center bg-red-500 hover:bg-red-600 text-white py-2 rounded-lg font-medium transition">
                  Delete
                </button>
              </form>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
      <div class="flex justify-center mt-10">
        <a href="/categories/create" class="bg-green-500 hover:bg-green-600 text-white font-semibold px-8 py-3 rounded-xl shadow transition">Add</a>
      </div>
    </div>
  </div>
</body>

</html>